
#================================================
## SAPPHIRE DDL SCRIPTS
#================================================

### VENDOR MASTER ###

DROP TABLE IF EXISTS `sapphire`.`vendor`;

CREATE TABLE `sapphire`.`vendor` (
  `VENDOR_ID` INT(5) ZEROFILL NOT NULL AUTO_INCREMENT,
  `VENDOR_NAME` VARCHAR(70) NULL,
  `VENDOR_ADDRESS` VARCHAR(100) NULL,
  `VENDOR_STATE` VARCHAR(2) NULL,
  `VENDOR_CITY` VARCHAR(2) NULL,
  `VENDOR_PIN` VARCHAR(6) NULL,
  `VENDOR_PHONE` VARCHAR(10) NULL,
  `VENDOR_COMMENTS` VARCHAR(200) NULL,
  `CREATED_USER` INT(4) NULL DEFAULT 0,
  `CREATED_TIMESTAMP` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_USER` INT(4) NULL DEFAULT 0,
  `MODIFIED_TIMESTAMP` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `DELETED` VARCHAR(1) NULL DEFAULT 'N',
  PRIMARY KEY (`VENDOR_ID`)  COMMENT 'Index for searching by Id',
  INDEX `VENDOR_NAME_UNIQUE` (`VENDOR_NAME` ASC)  COMMENT 'Index for searching by vendor name')
ENGINE = InnoDB
AUTO_INCREMENT = 1001
COMMENT = 'VENDOR MASTER TABLE';


### INVENTORY MASTER ###