
#================================================
## SAPPHIRE DDL SCRIPTS
#================================================

### VENDOR MASTER ###

DROP TABLE IF EXISTS `sapphire`.`vendor`;

CREATE TABLE `sapphire`.`vendor` (
  `VENDOR_ID` INT(5) ZEROFILL NOT NULL AUTO_INCREMENT,
  `VENDOR_NAME` VARCHAR(70) NOT NULL,
  `VENDOR_ADDRESS` VARCHAR(100) NULL,
  `VENDOR_STATE` VARCHAR(2) NULL,
  `VENDOR_CITY` VARCHAR(2) NULL,
  `VENDOR_PIN` VARCHAR(6) NULL,
  `VENDOR_PHONE` VARCHAR(10) NULL,
  `VENDOR_COMMENTS` VARCHAR(200) NULL,
  `CREATED_USER` INT(4) NOT NULL DEFAULT 0,
  `CREATED_TIMESTAMP` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_USER` INT(4) NOT NULL DEFAULT 0,
  `MODIFIED_TIMESTAMP` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DELETED` VARCHAR(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (`VENDOR_ID`)  COMMENT 'Index for searching by Id',
  INDEX `VENDOR_NAME_UNIQUE` (`VENDOR_NAME` ASC)  COMMENT 'Index for searching by vendor name')
ENGINE = InnoDB
AUTO_INCREMENT = 1001
COMMENT = 'VENDOR MASTER TABLE';


### INVENTORY MASTER ###


DROP TABLE IF EXISTS `sapphire`.`inventory`;

CREATE TABLE `sapphire`.`inventory` (
  `ITEM_ID` INT(5) ZEROFILL NOT NULL AUTO_INCREMENT,
  `ITEM_BARCODE` VARCHAR(20) NULL,
  `ITEM_NAME` VARCHAR(200) NULL,
  `ITEM_TYPE` VARCHAR(2) NULL,
  `ITEM_QTY_TOTAL` INT(6) NULL DEFAULT 0,
  `ITEM_QTY_PEND` INT(6) NULL DEFAULT 0,
  `ITEM_RATE` DOUBLE NULL DEFAULT 0,
  `ITEM_VAT_PERC` DOUBLE NULL DEFAULT 0,
  `CREATED_USER` INT(4) NULL DEFAULT 0,
  `CREATED_TIMESTAMP` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_USER` INT(4) NULL,
  `MODIFIED_TIMESTAMP` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DELETED` VARCHAR(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (`ITEM_ID`),
  UNIQUE INDEX `BARCODE_UNIQUE` (`ITEM_BARCODE` ASC));
  
  
  
  ###  ORDER DETAILS ###
  
  
  DROP TABLE IF EXISTS `sapphire`.`orderdetails`;
  
  CREATE TABLE `sapphire`.`orderdetails` (
  `ORDER_ID` INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
  `ITEM_ID` INT(5) NOT NULL,
  `ITEM_QTY` INT(5) NOT NULL,
  `ITEM_SELL_PRC` DOUBLE NULL,
  `ITEM_NET_PRC` DOUBLE NULL,
  `ITEM_VAT` DOUBLE NULL,
  `ITEM_VAT_PER` INT(2) NULL,
  `ITEM_GROSS_PRC` DOUBLE NULL,
  `ITEM_DISC_AMT` DOUBLE NULL,
  `ORDER_DATE` DATE NULL,
  `CREATED_TIMESTAMP` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_USER` INT(4) NULL DEFAULT 0,
  `MODIFIED_TIMESTAMP` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_USER` INT(4) NULL DEFAULT 0,
  `DELETED` VARCHAR(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (`ORDER_ID`, `ITEM_ID`),
  INDEX `ORD_DET_INDX` (`ORDER_ID` ASC, `ITEM_ID` ASC));
  
  
  
  ### ORDER CUST ###
  
    DROP TABLE IF EXISTS `sapphire`.`order_customer`;
  
	CREATE TABLE `sapphire`.`order_customer` (
	  `ORDER_ID` INT(10) NOT NULL,
	  `CUST_ID` INT(10) NOT NULL,
	  `ORDER_GROSS_AMT` VARCHAR(45) NULL,
	  `ORDER_GROSS_VAT` VARCHAR(45) NULL,
	  `INVOICE_ID` VARCHAR(45) NULL,
	  `ORDER_DATE` DATE NULL,
	  `COMMENTS` VARCHAR(200) NULL,
	  `ORDER_COMPLETED` VARCHAR(1) NULL DEFAULT 'N',
	  `CREATED_USER` VARCHAR(4) NULL,
	  `CREATED_TIMESTAMP` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	  `MODIFIED_USER` VARCHAR(4) NULL,
	  `MODIFIED_TIMESTAMP` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	  `DELETED` VARCHAR(1) NULL DEFAULT 'N',
	  PRIMARY KEY (`ORDER_ID`, `CUST_ID`));
  
  

### STATE MASTER ###

DROP TABLE IF EXISTS `sapphire`.`state`;

CREATE TABLE `sapphire`.`state` (                                                                    
          `StateID` INT(11) NOT NULL AUTO_INCREMENT,                                              
          `CountryID` INT(11) NOT NULL,                                                           
          `StateName` VARCHAR(50) NOT NULL,                                                       
          `Notes` LONGTEXT,                                                                       
          `ChangedBy` VARCHAR(50) DEFAULT NULL,                                                   
          `ChangeDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,  
          PRIMARY KEY  (`StateID`)                                                                
        ) ENGINE=INNODB AUTO_INCREMENT=36 DEFAULT CHARSET=latin1
        

### CITI MASTER ###

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
DROP TABLE IF EXISTS `sapphire`.`cities`;

CREATE TABLE IF NOT EXISTS `sapphire`.`cities` (
  `city_id` int(11) NOT NULL AUTO_INCREMENT,
  `city_name` varchar(100) NOT NULL,
  `city_state` varchar(100) NOT NULL,
  PRIMARY KEY (`city_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1624 ;

